<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class License extends Model
{
    protected $fillable = [
        'license_no',
        'last_update',
        'business_name',
        'bus_name_2',
        'full_business_name',
        'mailing_address',
        'city',
        'state',
        'county',
        'zip_code',
        'country',
        'business_phone',
        'business_type',
        'issue_date',
        'reissue_date',
        'expiration_date',
        'inactivation_date',
        'reactivation_date',
        'pending_suspension',
        'pending_class_removal',
        'pending_class_replace',
        'primary_status',
        'secondary_status',
        'classifications',
        'asbestos_reg',
        'workers_comp_coverage_type',
        'wc_insurance_company',
        'wc_policy_number',
        'wc_effective_date',
        'wc_expiration_date',
        'wc_cancellation_date',
        'wc_suspend_date',
        'cb_surety_company',
        'cb_number',
        'cb_effective_date',
        'cb_cancellation_date',
        'cb_amount',
        'wb_surety_company',
        'wb_number',
        'wb_effective_date',
        'wb_cancellation_date',
        'wb_amount',
        'db_surety_company',
        'db_number',
        'db_effective_date',
        'db_cancellation_date',
        'db_amount',
        'date_required',
        'discp_case_region',
        'db_bond_reason',
        'db_case_no',
        'name_tp_2',
    ];

    protected $casts = [
        'last_update' => 'date',
        'issue_date' => 'date',
        'reissue_date' => 'date',
        'expiration_date' => 'date',
        'inactivation_date' => 'date',
        'reactivation_date' => 'date',
        'wc_effective_date' => 'date',
        'wc_expiration_date' => 'date',
        'wc_cancellation_date' => 'date',
        'wc_suspend_date' => 'date',
        'cb_effective_date' => 'date',
        'cb_cancellation_date' => 'date',
        'wb_effective_date' => 'date',
        'wb_cancellation_date' => 'date',
        'db_effective_date' => 'date',
        'db_cancellation_date' => 'date',
        'date_required' => 'date',
        'cb_amount' => 'decimal:2',
        'wb_amount' => 'decimal:2',
        'db_amount' => 'decimal:2',
    ];
}
